name: Publish Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  resolve-package:
    name: Resolve package
    runs-on: ubuntu-latest

    outputs:
      package_dir: ${{ steps.resolve.outputs.package_dir }}
      package_name: ${{ steps.resolve.outputs.package_name }}
      package_version: ${{ steps.resolve.outputs.package_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Resolve release target
        id: resolve
        run: deno run --allow-env --allow-read --allow-write .github/workflows/scripts/resolve_release.ts

  publish:
    if: startsWith(github.event.release.target_commitish, 'releases/')
    name: Publish
    runs-on: ubuntu-latest
    needs: resolve-package
    environment:
      name: release
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to JSR
        working-directory: ${{ needs.resolve-package.outputs.package_dir }}
        run: npx jsr publish --dry-run
